### ISSUE TITLE
Modeling Friendship/Followship

### ISSUE THREAD

**Issue by woongy** [fools-gold/swindler#7]
유저들 사이 친구 관계 혹은 팔로우 관계에 대해서 얘기해보아요. 친구 관계라고 하면 요청을 보내면 수락하고 상호 친구 관계가 되는 거고, 팔로우 관계라고 하면 내가 일방적으로 누구 소식을 받아보는 관계가 되는 거를 말합니다. 전자는 페이스북 후자는 트위터.

**Comment by woongy** [comment]
팔로우 관계로 하면 좋겠다고 생각해서 그렇게 구현할건데, 다른 의견 있으면 주세영

**Comment by spilist** [comment]
팔로우가 친구보다 더 좋겠다고 생각한 이유는 무엇인가요

**Comment by woongy** [comment]
친구는 무겁기 때문입니다 (초대/수락하는 과정이)
