### ISSUE TITLE
Allowing which users can write stories about someone

### ISSUE THREAD

**Issue by woongy** [fools-gold/swindler#9]
#4 에서 `Story`를 추가하게 될 텐데, #7 에서 추가한 팔로우 관계와 함께 생각해보면:
1. users can write stories about any users
2. users can write stories about other users they are following
3. users can write stories about other users who are following them
4. users can write stories about other users if they are following each other

모든 옵션에는 각각 나름대로 말이 되는 이유가 있어서 선택하기 나름이고, 어떤 옵션을 선택하는가에 따라서 추가로 해야할 일이 생길 수도 있는데 뭐가 좋을지 생각해 봅시다.

**Comment by JBWoo** [comment]
1번이랑 4번의 차이를 보면 
1 번의 경우에는 같이 플레이한 친구가 following 하지 않은 상태에서라도 글을 적을 수 있고, 글 작성 이후에 following을 할 수도 있다는 장점이 있는 반면, 뜬금없는 사람이 이상한 포스트를 올릴 수도 있다는 단점이 있을 것 같고,
4번의 경우에는 확실히 친구관계인 사람이 글을 올리지만, following을 하기 전에는 글을 못 올리기 때문에 만약 처음 같이 플레이 하는 사람이라면 글을 올리기 위한 step에 following 하는 스텝이 추가되어서 더 길어질 것 같다. 
그런데 처음에 우리가 생각했던게, 보드게임하면서 놓치기 싫은 순간순간을 기록하는 게 메인이었던것 같아서 글을 더 쉽게 올리는게 더 맞는 방향이 아닐까 생각함. 

그래서 나는 1번.

**Comment by spilist** [comment]
'누구에 대한 스토리인가'를 쓰는 방법은, 그 사람의 아이디/닉네임을 쓰면 자동완성이 되는 형태일텐데
2, 3, 4번의 경우 그 유저 풀 안에서 검색해서 자동완성을 해주면 되고, 그러면 유저가 그중에 선택하기도 쉽지만
1번의 경우 전체 풀에서 찾아야 하니까 유저가 선택하기가 오히려 어려울 수도 있음.

이 문제를 풀자면 자동완성으로 찾아진 유저들 중 나와 관계가 있을 가능성이 높은 유저들(친구의 친구라든가, 친구가 그 사람에 대한 스토리를 썼다든가)을 정의하는 무언가가 있어야 한다고 생각.
이게 곧 Who to Follow 기능을 구현하는 셈이 될 것 같은데, Story를 작성하는 것이 이 서비스 개발에서 가장 핵심이 되는 기능이니 처음에는 Who to Follow 없이 모든 풀을 다 보여주는 식으로 개발하게 될 것임. 그러면 유저 입장에서 불편하겠지.

그래서 나는 5번인 "users can write stories about other users they are following or who are following them"이 어떨까 싶음. 이렇게 한 다음 나중에 Who to Follow를 만들면서 1번으로 확장해도 되고, 안 바꿔도 되고.

@JBWoo 의 "following을 하기 전에는 글을 못 올리기 때문에 만약 처음 같이 플레이 하는 사람이라면 글을 올리기 위한 step에 following 하는 스텝이 추가되어서 더 길어질 것 같다." 에 대해서는, 
해당 유저를 검색한다 -> 유저의 프로필 페이지로 간다 -> Follow한다 -> 프로필 페이지에서 '그 유저에 대한 스토리 쓰기' 버튼을 누른다 
와 같이 시나리오를 생각한다면 아주 불편하지는 않을 것 같음.

**Comment by woongy** [comment]
@spilist 두 가지 문제를 섞어서 말하고 있음: 1. 누구에게 스토리를 쓸 수 있는가 (권한) 2. 스토리 쓸 유저를 어떻게 찾게 해줄 것인가 (UX) 2 때문에 1을 바꿀 수는 없지.

나도 1번을 좋게 보는데 이유는:
- 2는 follow request 같은 과정이 없는 이상 1과 다를 게 없음
- 3은 내가 누구에게 스토리를 쓸 수 있는지 선택할 권리가 나한테 없다는 점에서 이상함
- 4는 폐쇄적인 관계망을 지향하게 되는 건데, 그러고 싶지는 않음

물론 1로 한다면 @JBWoo 가 말했듯이 트롤을 거를 수 있어야 하고 (ex. "저 사람 나랑 플레이 한 적 없는데? 너 신고") 이걸 첫 버전에서 할 필요는 물론 없음.

swindler를 메시징 서비스에 비유해보면, 내가 다른 사람에게 보내는 메시지를 누구나 볼 수 있다는 점이 크게 다름. 보내는 메시지의 성격 때문인데, 넓은 광장에서 누구를 지칭해서 메시지를 보내지만 다른 사람들도 같이 듣고 즐기기 위해서– 라고 볼 수 있을 듯. (트위터랑 똑같지)

스토리 보낼 사람을 어떻게 고르게 할거냐, 자동 완성은 어떻게 할거냐, 같은 주제는 스토리 작성 폼을 얘기할 때 고민하면 되는 주제인 거 같음!

사족: @spilist 가 마지막에 얘기한 시나리오는 아주 불편한 거라는 데 한 표 ㅎ_ㅎ

**Comment by spilist** [comment]
트위터처럼 생각한다면 신경 안써도 되겠지만, 후보로 5. users can write stories about other users they are following or who are following them 을 추가할 필요는 있는듯.

**Comment by woongy** [comment]
나는 2와 3이 별로인 이유로 여전히 5도 별로인데, 5처럼 제한하면 서비스 적으로 어떤 의미가 있는 거 같아?

**Comment by spilist** [comment]
1에 비해 5가 낫다는 뜻은 아니고 full set이 아니라는 점에서 추가하자고 한거 ㅋㅋ

**Comment by JBWoo** [comment]
위에 것들을 보다가 보니깐, 드는 생각이 일단 following 이라는 형태의 관계설정기능을 사용한다는게 전제가 되어있는 것 같은데 이것도 좀 논의해볼 필요가 있을 듯.
사실 나는 처음 facebook 처럼 친구관계 설정을 하는 거라고 생각을 했었거든. (한 사람이 친구 요청을 하고 수락을 하면 친구가 되는 형태로)
이건 follow 라는 다른 형태 인것 같아서 follow 랑 친구요청/수락 중 어떤 걸 선택할지도 같이 이야기 해보면 어떨까? 이건 다른 이슈인 것 같기도 함.

**Comment by woongy** [comment]
어.. 그 이슈가 #7 이었어..

**Comment by woongy** [comment]
추가 의견 없으면 1로 가는 것으로 하고 이슈 닫을게영
